export type MerchantCategory =
  | "Apparel"
  | "Shoes"
  | "Home"
  | "Mattresses"
  | "Fitness"
  | "Wellness"
  | "Electronics"
  | "Outdoor"
  | "Travel"
  | "Jewelry"
  | "Beauty"
  | "Other";

export type Merchant = {
  id: string;
  name: string;
  category: MerchantCategory;
  domain: string;
  logoUrl: string;
  description: string;
  shoppable: boolean;
  shopifyDomain?: string;
};

function logo(domain: string) {
  return `https://logo.clearbit.com/${domain}`;
}

export const MERCHANTS: Merchant[] = [
  {
    id: "allbirds",
    name: "Allbirds",
    category: "Shoes",
    domain: "allbirds.com",
    logoUrl: logo("allbirds.com"),
    description: "Sustainable everyday sneakers and apparel.",
    shoppable: true,
    shopifyDomain: "www.allbirds.com",
  },
  {
    id: "rothys",
    name: "Rothy's",
    category: "Shoes",
    domain: "rothys.com",
    logoUrl: logo("rothys.com"),
    description: "Shoes and bags made from recycled plastic.",
    shoppable: true,
    shopifyDomain: "www.rothys.com",
  },
  {
    id: "taylor_stitch",
    name: "Taylor Stitch",
    category: "Apparel",
    domain: "taylorstitch.com",
    logoUrl: logo("taylorstitch.com"),
    description: "Responsibly made menswear built to last.",
    shoppable: true,
    shopifyDomain: "www.taylorstitch.com",
  },
  {
    id: "everlane",
    name: "Everlane",
    category: "Apparel",
    domain: "everlane.com",
    logoUrl: logo("everlane.com"),
    description: "Transparent pricing on everyday essentials.",
    shoppable: true,
    shopifyDomain: "www.everlane.com",
  },
  {
    id: "casper",
    name: "Casper",
    category: "Mattresses",
    domain: "casper.com",
    logoUrl: logo("casper.com"),
    description: "Award-winning mattresses and sleep products.",
    shoppable: true,
    shopifyDomain: "www.casper.com",
  },
  {
    id: "tuft_and_needle",
    name: "Tuft & Needle",
    category: "Mattresses",
    domain: "tuftandneedle.com",
    logoUrl: logo("tuftandneedle.com"),
    description: "Pressure-relieving foam mattresses and bedding.",
    shoppable: true,
    shopifyDomain: "www.tuftandneedle.com",
  },
  {
    id: "brooklinen",
    name: "Brooklinen",
    category: "Home",
    domain: "brooklinen.com",
    logoUrl: logo("brooklinen.com"),
    description: "Premium sheets, bedding, and home essentials.",
    shoppable: true,
    shopifyDomain: "www.brooklinen.com",
  },
  {
    id: "parachute",
    name: "Parachute",
    category: "Home",
    domain: "parachutehome.com",
    logoUrl: logo("parachutehome.com"),
    description: "Bedding, bath, and home goods made with care.",
    shoppable: true,
    shopifyDomain: "www.parachutehome.com",
  },
  {
    id: "therabody",
    name: "Therabody",
    category: "Wellness",
    domain: "therabody.com",
    logoUrl: logo("therabody.com"),
    description: "Percussive therapy and recovery devices.",
    shoppable: true,
    shopifyDomain: "www.therabody.com",
  },
  {
    id: "jackery",
    name: "Jackery",
    category: "Outdoor",
    domain: "jackery.com",
    logoUrl: logo("jackery.com"),
    description: "Portable power stations and solar generators.",
    shoppable: true,
    shopifyDomain: "www.jackery.com",
  },
  {
    id: "gymshark",
    name: "Gymshark",
    category: "Fitness",
    domain: "gymshark.com",
    logoUrl: logo("gymshark.com"),
    description: "Performance gym wear and fitness apparel.",
    shoppable: true,
    shopifyDomain: "www.gymshark.com",
  },
  {
    id: "bombas",
    name: "Bombas",
    category: "Apparel",
    domain: "bombas.com",
    logoUrl: logo("bombas.com"),
    description: "Comfort-focused socks, underwear, and apparel.",
    shoppable: true,
    shopifyDomain: "www.bombas.com",
  },
  {
    id: "mejuri",
    name: "Mejuri",
    category: "Jewelry",
    domain: "mejuri.com",
    logoUrl: logo("mejuri.com"),
    description: "Fine jewelry for everyday wear.",
    shoppable: true,
    shopifyDomain: "www.mejuri.com",
  },
  {
    id: "ridge",
    name: "Ridge Wallet",
    category: "Other",
    domain: "ridge.com",
    logoUrl: logo("ridge.com"),
    description: "Minimalist wallets and everyday carry.",
    shoppable: true,
    shopifyDomain: "www.ridge.com",
  },
  {
    id: "dr_squatch",
    name: "Dr. Squatch",
    category: "Beauty",
    domain: "drsquatch.com",
    logoUrl: logo("drsquatch.com"),
    description: "Natural soaps and grooming for men.",
    shoppable: true,
    shopifyDomain: "www.drsquatch.com",
  },
  {
    id: "cotopaxi",
    name: "Cotopaxi",
    category: "Outdoor",
    domain: "cotopaxi.com",
    logoUrl: logo("cotopaxi.com"),
    description: "Colorful outdoor gear with a mission.",
    shoppable: true,
    shopifyDomain: "www.cotopaxi.com",
  },
  {
    id: "outdoor_voices",
    name: "Outdoor Voices",
    category: "Apparel",
    domain: "outdoorvoices.com",
    logoUrl: logo("outdoorvoices.com"),
    description: "Activewear for recreation and everyday movement.",
    shoppable: true,
    shopifyDomain: "www.outdoorvoices.com",
  },
  {
    id: "cuts",
    name: "Cuts Clothing",
    category: "Apparel",
    domain: "cutsclothing.com",
    logoUrl: logo("cutsclothing.com"),
    description: "Premium performance-lifestyle menswear.",
    shoppable: true,
    shopifyDomain: "www.cutsclothing.com",
  },
  {
    id: "true_classic",
    name: "True Classic",
    category: "Apparel",
    domain: "trueclassic.com",
    logoUrl: logo("trueclassic.com"),
    description: "Fitted tees and everyday basics for men.",
    shoppable: true,
    shopifyDomain: "www.trueclassic.com",
  },
  {
    id: "marine_layer",
    name: "Marine Layer",
    category: "Apparel",
    domain: "marinelayer.com",
    logoUrl: logo("marinelayer.com"),
    description: "Soft, casual everyday clothing.",
    shoppable: true,
    shopifyDomain: "www.marinelayer.com",
  },
  {
    id: "rhone",
    name: "Rhone",
    category: "Apparel",
    domain: "rhone.com",
    logoUrl: logo("rhone.com"),
    description: "Premium performance menswear.",
    shoppable: true,
    shopifyDomain: "www.rhone.com",
  },
  {
    id: "bearaby",
    name: "Bearaby",
    category: "Home",
    domain: "bearaby.com",
    logoUrl: logo("bearaby.com"),
    description: "Organic weighted blankets and sleep products.",
    shoppable: true,
    shopifyDomain: "www.bearaby.com",
  },
  {
    id: "peak_design",
    name: "Peak Design",
    category: "Electronics",
    domain: "peakdesign.com",
    logoUrl: logo("peakdesign.com"),
    description: "Camera bags, straps, and everyday carry gear.",
    shoppable: true,
    shopifyDomain: "www.peakdesign.com",
  },
  {
    id: "mvmt",
    name: "MVMT",
    category: "Jewelry",
    domain: "mvmt.com",
    logoUrl: logo("mvmt.com"),
    description: "Modern watches and accessories.",
    shoppable: true,
    shopifyDomain: "www.mvmt.com",
  },
  {
    id: "pura_vida",
    name: "Pura Vida",
    category: "Jewelry",
    domain: "puravidabracelets.com",
    logoUrl: logo("puravidabracelets.com"),
    description: "Handmade bracelets and jewelry.",
    shoppable: true,
    shopifyDomain: "www.puravidabracelets.com",
  },
  {
    id: "vuori",
    name: "Vuori",
    category: "Apparel",
    domain: "vuoriclothing.com",
    logoUrl: logo("vuoriclothing.com"),
    description: "Performance apparel for everyday life.",
    shoppable: true,
    shopifyDomain: "www.vuoriclothing.com",
  },
  {
    id: "figs",
    name: "FIGS",
    category: "Apparel",
    domain: "wearfigs.com",
    logoUrl: logo("wearfigs.com"),
    description: "Modern medical scrubs and healthcare apparel.",
    shoppable: true,
    shopifyDomain: "www.wearfigs.com",
  },
  {
    id: "nomad",
    name: "Nomad Goods",
    category: "Electronics",
    domain: "nomadgoods.com",
    logoUrl: logo("nomadgoods.com"),
    description: "Premium phone cases and charging accessories.",
    shoppable: true,
    shopifyDomain: "www.nomadgoods.com",
  },
  {
    id: "solo_stove",
    name: "Solo Stove",
    category: "Outdoor",
    domain: "solostove.com",
    logoUrl: logo("solostove.com"),
    description: "Smokeless fire pits and outdoor cooking.",
    shoppable: true,
    shopifyDomain: "www.solostove.com",
  },

  // Powered by real-time web search (Anthropic web_search tool) — not Shopify
  {
    id: "amazon",
    name: "Amazon",
    category: "Other",
    domain: "amazon.com",
    logoUrl: logo("amazon.com"),
    description: "Anything and everything — Affirm at checkout.",
    shoppable: true,
  },

  // ── Apparel ────────────────────────────────────────────────────────────────
  {
    id: "reformation",
    name: "Reformation",
    category: "Apparel",
    domain: "thereformation.com",
    logoUrl: logo("thereformation.com"),
    description: "Sustainable women's clothing and dresses.",
    shoppable: true,
    shopifyDomain: "www.thereformation.com",
  },
  {
    id: "faherty",
    name: "Faherty Brand",
    category: "Apparel",
    domain: "fahertybrand.com",
    logoUrl: logo("fahertybrand.com"),
    description: "Sustainably crafted coastal lifestyle clothing.",
    shoppable: true,
    shopifyDomain: "www.fahertybrand.com",
  },
  {
    id: "buck_mason",
    name: "Buck Mason",
    category: "Apparel",
    domain: "buckmason.com",
    logoUrl: logo("buckmason.com"),
    description: "Classic American menswear made to last.",
    shoppable: true,
    shopifyDomain: "www.buckmason.com",
  },
  {
    id: "mack_weldon",
    name: "Mack Weldon",
    category: "Apparel",
    domain: "mackweldon.com",
    logoUrl: logo("mackweldon.com"),
    description: "Premium men's underwear, socks, and basics.",
    shoppable: true,
    shopifyDomain: "www.mackweldon.com",
  },
  {
    id: "todd_snyder",
    name: "Todd Snyder",
    category: "Apparel",
    domain: "toddsnyder.com",
    logoUrl: logo("toddsnyder.com"),
    description: "Modern American menswear and tailoring.",
    shoppable: true,
    shopifyDomain: "www.toddsnyder.com",
  },
  {
    id: "rowing_blazers",
    name: "Rowing Blazers",
    category: "Apparel",
    domain: "rowingblazers.com",
    logoUrl: logo("rowingblazers.com"),
    description: "Irreverent preppy clothing and blazers.",
    shoppable: true,
    shopifyDomain: "www.rowingblazers.com",
  },
  {
    id: "madhappy",
    name: "Madhappy",
    category: "Apparel",
    domain: "madhappy.com",
    logoUrl: logo("madhappy.com"),
    description: "Optimistic streetwear and mental health advocacy.",
    shoppable: true,
    shopifyDomain: "www.madhappy.com",
  },
  {
    id: "chubbies",
    name: "Chubbies",
    category: "Apparel",
    domain: "chubbiesshorts.com",
    logoUrl: logo("chubbiesshorts.com"),
    description: "Fun weekend shorts and casual apparel.",
    shoppable: true,
    shopifyDomain: "www.chubbiesshorts.com",
  },
  {
    id: "farm_rio",
    name: "Farm Rio",
    category: "Apparel",
    domain: "farmrio.com",
    logoUrl: logo("farmrio.com"),
    description: "Colorful Brazilian fashion and resort wear.",
    shoppable: true,
    shopifyDomain: "www.farmrio.com",
  },
  {
    id: "lunya",
    name: "Lunya",
    category: "Apparel",
    domain: "lunya.co",
    logoUrl: logo("lunya.co"),
    description: "Elevated sleepwear and loungewear for women.",
    shoppable: true,
    shopifyDomain: "www.lunya.co",
  },
  {
    id: "eberjey",
    name: "Eberjey",
    category: "Apparel",
    domain: "eberjey.com",
    logoUrl: logo("eberjey.com"),
    description: "Soft, luxurious loungewear and intimates.",
    shoppable: true,
    shopifyDomain: "www.eberjey.com",
  },
  {
    id: "parade",
    name: "Parade",
    category: "Apparel",
    domain: "yourparade.com",
    logoUrl: logo("yourparade.com"),
    description: "Colorful, sustainable underwear and bralettes.",
    shoppable: true,
    shopifyDomain: "www.yourparade.com",
  },
  {
    id: "girlfriend_collective",
    name: "Girlfriend Collective",
    category: "Apparel",
    domain: "girlfriend.com",
    logoUrl: logo("girlfriend.com"),
    description: "Sustainable activewear made from recycled materials.",
    shoppable: true,
    shopifyDomain: "www.girlfriend.com",
  },
  {
    id: "aviator_nation",
    name: "Aviator Nation",
    category: "Apparel",
    domain: "aviatornation.com",
    logoUrl: logo("aviatornation.com"),
    description: "Vintage-inspired hand-sewn California sweatshirts.",
    shoppable: true,
    shopifyDomain: "www.aviatornation.com",
  },
  {
    id: "ministry_of_supply",
    name: "Ministry of Supply",
    category: "Apparel",
    domain: "ministryofsupply.com",
    logoUrl: logo("ministryofsupply.com"),
    description: "Performance professional clothing for work.",
    shoppable: true,
    shopifyDomain: "www.ministryofsupply.com",
  },
  {
    id: "tracksmith",
    name: "Tracksmith",
    category: "Apparel",
    domain: "tracksmith.com",
    logoUrl: logo("tracksmith.com"),
    description: "Premium running apparel for serious runners.",
    shoppable: true,
    shopifyDomain: "www.tracksmith.com",
  },
  {
    id: "janji",
    name: "Janji",
    category: "Apparel",
    domain: "runjanji.com",
    logoUrl: logo("runjanji.com"),
    description: "Running apparel that funds clean water access.",
    shoppable: true,
    shopifyDomain: "www.runjanji.com",
  },
  {
    id: "ganni",
    name: "Ganni",
    category: "Apparel",
    domain: "ganni.com",
    logoUrl: logo("ganni.com"),
    description: "Playful contemporary Scandinavian fashion.",
    shoppable: true,
    shopifyDomain: "www.ganni.com",
  },
  {
    id: "staud",
    name: "Staud",
    category: "Apparel",
    domain: "staud.clothing",
    logoUrl: logo("staud.clothing"),
    description: "Modern women's clothing, bags, and accessories.",
    shoppable: true,
    shopifyDomain: "www.staud.clothing",
  },
  {
    id: "loveshackfancy",
    name: "LoveShackFancy",
    category: "Apparel",
    domain: "loveshackfancy.com",
    logoUrl: logo("loveshackfancy.com"),
    description: "Romantic floral and feminine dresses.",
    shoppable: true,
    shopifyDomain: "www.loveshackfancy.com",
  },
  {
    id: "sezane",
    name: "Sézane",
    category: "Apparel",
    domain: "sezane.com",
    logoUrl: logo("sezane.com"),
    description: "French-inspired women's fashion.",
    shoppable: true,
    shopifyDomain: "www.sezane.com",
  },
  // ── Shoes ─────────────────────────────────────────────────────────────────
  {
    id: "thursday_boots",
    name: "Thursday Boots",
    category: "Shoes",
    domain: "thursdayboots.com",
    logoUrl: logo("thursdayboots.com"),
    description: "Quality everyday boots at honest prices.",
    shoppable: true,
    shopifyDomain: "www.thursdayboots.com",
  },
  {
    id: "tecovas",
    name: "Tecovas",
    category: "Shoes",
    domain: "tecovas.com",
    logoUrl: logo("tecovas.com"),
    description: "Handcrafted western boots and leather goods.",
    shoppable: true,
    shopifyDomain: "www.tecovas.com",
  },
  {
    id: "nisolo",
    name: "Nisolo",
    category: "Shoes",
    domain: "nisolo.com",
    logoUrl: logo("nisolo.com"),
    description: "Sustainably made leather shoes and accessories.",
    shoppable: true,
    shopifyDomain: "www.nisolo.com",
  },
  {
    id: "cariuma",
    name: "Cariuma",
    category: "Shoes",
    domain: "cariuma.com",
    logoUrl: logo("cariuma.com"),
    description: "Sustainable sneakers made from natural materials.",
    shoppable: true,
    shopifyDomain: "www.cariuma.com",
  },
  {
    id: "greats",
    name: "Greats",
    category: "Shoes",
    domain: "greats.com",
    logoUrl: logo("greats.com"),
    description: "Premium Brooklyn-made sneakers.",
    shoppable: true,
    shopifyDomain: "www.greats.com",
  },
  {
    id: "birdies",
    name: "Birdies",
    category: "Shoes",
    domain: "birdiesshoes.com",
    logoUrl: logo("birdiesshoes.com"),
    description: "Stylish women's flats with hidden comfort technology.",
    shoppable: true,
    shopifyDomain: "www.birdiesshoes.com",
  },
  {
    id: "oliver_cabell",
    name: "Oliver Cabell",
    category: "Shoes",
    domain: "olivercabell.com",
    logoUrl: logo("olivercabell.com"),
    description: "Transparent-supply-chain sneakers and bags.",
    shoppable: true,
    shopifyDomain: "www.olivercabell.com",
  },
  // ── Home & Kitchen ────────────────────────────────────────────────────────
  {
    id: "our_place",
    name: "Our Place",
    category: "Home",
    domain: "fromourplace.com",
    logoUrl: logo("fromourplace.com"),
    description: "The Always Pan and modern kitchen essentials.",
    shoppable: true,
    shopifyDomain: "www.fromourplace.com",
  },
  {
    id: "caraway",
    name: "Caraway",
    category: "Home",
    domain: "carawayhome.com",
    logoUrl: logo("carawayhome.com"),
    description: "Non-toxic ceramic cookware and bakeware.",
    shoppable: true,
    shopifyDomain: "www.carawayhome.com",
  },
  {
    id: "great_jones",
    name: "Great Jones",
    category: "Home",
    domain: "greatjonesgoods.com",
    logoUrl: logo("greatjonesgoods.com"),
    description: "Colorful cast iron and cookware for home cooks.",
    shoppable: true,
    shopifyDomain: "www.greatjonesgoods.com",
  },
  {
    id: "made_in",
    name: "Made In Cookware",
    category: "Home",
    domain: "madeincookware.com",
    logoUrl: logo("madeincookware.com"),
    description: "Professional-grade cookware for home cooks.",
    shoppable: true,
    shopifyDomain: "www.madeincookware.com",
  },
  {
    id: "snowe",
    name: "Snowe",
    category: "Home",
    domain: "snowehome.com",
    logoUrl: logo("snowehome.com"),
    description: "Minimalist, quality home essentials.",
    shoppable: true,
    shopifyDomain: "www.snowehome.com",
  },
  {
    id: "floyd",
    name: "Floyd",
    category: "Home",
    domain: "floydhome.com",
    logoUrl: logo("floydhome.com"),
    description: "Modern modular furniture built to last.",
    shoppable: true,
    shopifyDomain: "www.floydhome.com",
  },
  {
    id: "schoolhouse",
    name: "Schoolhouse",
    category: "Home",
    domain: "schoolhouse.com",
    logoUrl: logo("schoolhouse.com"),
    description: "Lighting, hardware, and home goods with character.",
    shoppable: true,
    shopifyDomain: "www.schoolhouse.com",
  },
  {
    id: "east_fork",
    name: "East Fork",
    category: "Home",
    domain: "eastfork.com",
    logoUrl: logo("eastfork.com"),
    description: "Handmade American pottery and ceramics.",
    shoppable: true,
    shopifyDomain: "www.eastfork.com",
  },
  {
    id: "brightland",
    name: "Brightland",
    category: "Home",
    domain: "brightland.co",
    logoUrl: logo("brightland.co"),
    description: "Small-batch California olive oil and vinegar.",
    shoppable: true,
    shopifyDomain: "www.brightland.co",
  },
  {
    id: "boll_and_branch",
    name: "Boll & Branch",
    category: "Home",
    domain: "bollandbranch.com",
    logoUrl: logo("bollandbranch.com"),
    description: "Organic cotton sheets and bedding.",
    shoppable: true,
    shopifyDomain: "www.bollandbranch.com",
  },
  {
    id: "cozy_earth",
    name: "Cozy Earth",
    category: "Home",
    domain: "cozyearth.com",
    logoUrl: logo("cozyearth.com"),
    description: "Bamboo bedding, loungewear, and towels.",
    shoppable: true,
    shopifyDomain: "www.cozyearth.com",
  },
  {
    id: "buffy",
    name: "Buffy",
    category: "Home",
    domain: "buffy.co",
    logoUrl: logo("buffy.co"),
    description: "Comforters and pillows made from recycled materials.",
    shoppable: true,
    shopifyDomain: "www.buffy.co",
  },
  // ── Beauty & Grooming ─────────────────────────────────────────────────────
  {
    id: "glossier",
    name: "Glossier",
    category: "Beauty",
    domain: "glossier.com",
    logoUrl: logo("glossier.com"),
    description: "Skin-first makeup and skincare essentials.",
    shoppable: true,
    shopifyDomain: "www.glossier.com",
  },
  {
    id: "summer_fridays",
    name: "Summer Fridays",
    category: "Beauty",
    domain: "summerfridays.com",
    logoUrl: logo("summerfridays.com"),
    description: "Clean skincare for glowing, healthy skin.",
    shoppable: true,
    shopifyDomain: "www.summerfridays.com",
  },
  {
    id: "glow_recipe",
    name: "Glow Recipe",
    category: "Beauty",
    domain: "glowrecipe.com",
    logoUrl: logo("glowrecipe.com"),
    description: "Fruit-powered skincare that actually works.",
    shoppable: true,
    shopifyDomain: "www.glowrecipe.com",
  },
  {
    id: "ilia",
    name: "ILIA Beauty",
    category: "Beauty",
    domain: "iliabeauty.com",
    logoUrl: logo("iliabeauty.com"),
    description: "Clean, performance-driven makeup.",
    shoppable: true,
    shopifyDomain: "www.iliabeauty.com",
  },
  {
    id: "hero_cosmetics",
    name: "Hero Cosmetics",
    category: "Beauty",
    domain: "herocosmetics.us",
    logoUrl: logo("herocosmetics.us"),
    description: "Acne-focused skincare, home of Mighty Patch.",
    shoppable: true,
    shopifyDomain: "www.herocosmetics.us",
  },
  {
    id: "herbivore",
    name: "Herbivore Botanicals",
    category: "Beauty",
    domain: "herbivorebotanicals.com",
    logoUrl: logo("herbivorebotanicals.com"),
    description: "Natural, plant-based skincare.",
    shoppable: true,
    shopifyDomain: "www.herbivorebotanicals.com",
  },
  {
    id: "youth_to_the_people",
    name: "Youth To The People",
    category: "Beauty",
    domain: "youthtothepeople.com",
    logoUrl: logo("youthtothepeople.com"),
    description: "Superfood skincare powered by kale and green tea.",
    shoppable: true,
    shopifyDomain: "www.youthtothepeople.com",
  },
  {
    id: "beardbrand",
    name: "Beardbrand",
    category: "Beauty",
    domain: "beardbrand.com",
    logoUrl: logo("beardbrand.com"),
    description: "Premium beard and men's grooming products.",
    shoppable: true,
    shopifyDomain: "www.beardbrand.com",
  },
  {
    id: "every_man_jack",
    name: "Every Man Jack",
    category: "Beauty",
    domain: "everymanjack.com",
    logoUrl: logo("everymanjack.com"),
    description: "Natural men's grooming and body care.",
    shoppable: true,
    shopifyDomain: "www.everymanjack.com",
  },
  {
    id: "malin_goetz",
    name: "Malin + Goetz",
    category: "Beauty",
    domain: "malinandgoetz.com",
    logoUrl: logo("malinandgoetz.com"),
    description: "Simple, effective apothecary skin and hair care.",
    shoppable: true,
    shopifyDomain: "www.malinandgoetz.com",
  },
  // ── Jewelry & Watches ─────────────────────────────────────────────────────
  {
    id: "gorjana",
    name: "Gorjana",
    category: "Jewelry",
    domain: "gorjana.com",
    logoUrl: logo("gorjana.com"),
    description: "Demi-fine everyday jewelry.",
    shoppable: true,
    shopifyDomain: "www.gorjana.com",
  },
  {
    id: "catbird",
    name: "Catbird",
    category: "Jewelry",
    domain: "catbirdnyc.com",
    logoUrl: logo("catbirdnyc.com"),
    description: "Handmade fine jewelry from Brooklyn.",
    shoppable: true,
    shopifyDomain: "www.catbirdnyc.com",
  },
  {
    id: "ana_luisa",
    name: "Ana Luisa",
    category: "Jewelry",
    domain: "analuisa.com",
    logoUrl: logo("analuisa.com"),
    description: "Sustainable fine-like jewelry at accessible prices.",
    shoppable: true,
    shopifyDomain: "www.analuisa.com",
  },
  {
    id: "missoma",
    name: "Missoma",
    category: "Jewelry",
    domain: "missoma.com",
    logoUrl: logo("missoma.com"),
    description: "Contemporary gold jewelry for everyday wear.",
    shoppable: true,
    shopifyDomain: "www.missoma.com",
  },
  {
    id: "vrai",
    name: "VRAI",
    category: "Jewelry",
    domain: "vrai.com",
    logoUrl: logo("vrai.com"),
    description: "Sustainably created diamond jewelry.",
    shoppable: true,
    shopifyDomain: "www.vrai.com",
  },
  // ── Bags & Luggage ────────────────────────────────────────────────────────
  {
    id: "away",
    name: "Away",
    category: "Other",
    domain: "awaytravel.com",
    logoUrl: logo("awaytravel.com"),
    description: "Thoughtfully designed luggage and travel accessories.",
    shoppable: true,
    shopifyDomain: "www.awaytravel.com",
  },
  {
    id: "dagne_dover",
    name: "Dagne Dover",
    category: "Other",
    domain: "dagnedover.com",
    logoUrl: logo("dagnedover.com"),
    description: "Organized, functional bags and accessories.",
    shoppable: true,
    shopifyDomain: "www.dagnedover.com",
  },
  {
    id: "paravel",
    name: "Paravel",
    category: "Other",
    domain: "tourparavel.com",
    logoUrl: logo("tourparavel.com"),
    description: "Sustainable travel bags and luggage.",
    shoppable: true,
    shopifyDomain: "www.tourparavel.com",
  },
  {
    id: "lo_and_sons",
    name: "Lo & Sons",
    category: "Other",
    domain: "loandsons.com",
    logoUrl: logo("loandsons.com"),
    description: "Travel and work bags designed by women, for women.",
    shoppable: true,
    shopifyDomain: "www.loandsons.com",
  },
  {
    id: "bellroy",
    name: "Bellroy",
    category: "Other",
    domain: "bellroy.com",
    logoUrl: logo("bellroy.com"),
    description: "Slim wallets, bags, and phone cases.",
    shoppable: true,
    shopifyDomain: "www.bellroy.com",
  },
  {
    id: "aer",
    name: "Aer",
    category: "Other",
    domain: "aersf.com",
    logoUrl: logo("aersf.com"),
    description: "Clean, technical bags for work and gym.",
    shoppable: true,
    shopifyDomain: "www.aersf.com",
  },
  // ── Electronics & Tech Accessories ───────────────────────────────────────
  {
    id: "casetify",
    name: "Casetify",
    category: "Electronics",
    domain: "casetify.com",
    logoUrl: logo("casetify.com"),
    description: "Custom and artistic phone cases and accessories.",
    shoppable: true,
    shopifyDomain: "www.casetify.com",
  },
  {
    id: "native_union",
    name: "Native Union",
    category: "Electronics",
    domain: "nativeunion.com",
    logoUrl: logo("nativeunion.com"),
    description: "Premium cables, chargers, and desk accessories.",
    shoppable: true,
    shopifyDomain: "www.nativeunion.com",
  },
  {
    id: "moment",
    name: "Moment",
    category: "Electronics",
    domain: "shopmoment.com",
    logoUrl: logo("shopmoment.com"),
    description: "Mobile photography lenses and gear.",
    shoppable: true,
    shopifyDomain: "www.shopmoment.com",
  },
  {
    id: "dbrand",
    name: "Dbrand",
    category: "Electronics",
    domain: "dbrand.com",
    logoUrl: logo("dbrand.com"),
    description: "Phone and device skins, cases, and covers.",
    shoppable: true,
    shopifyDomain: "www.dbrand.com",
  },
  {
    id: "twelve_south",
    name: "Twelve South",
    category: "Electronics",
    domain: "twelvesouth.com",
    logoUrl: logo("twelvesouth.com"),
    description: "Premium Apple accessories and lifestyle products.",
    shoppable: true,
    shopifyDomain: "www.twelvesouth.com",
  },
  // ── Outdoor & Sports ──────────────────────────────────────────────────────
  {
    id: "topo_designs",
    name: "Topo Designs",
    category: "Outdoor",
    domain: "topodesigns.com",
    logoUrl: logo("topodesigns.com"),
    description: "Colorado-made bags and outdoor apparel.",
    shoppable: true,
    shopifyDomain: "www.topodesigns.com",
  },
  {
    id: "rumpl",
    name: "Rumpl",
    category: "Outdoor",
    domain: "rumpl.com",
    logoUrl: logo("rumpl.com"),
    description: "Packable blankets for adventures and home.",
    shoppable: true,
    shopifyDomain: "www.rumpl.com",
  },
  {
    id: "darn_tough",
    name: "Darn Tough",
    category: "Outdoor",
    domain: "darntough.com",
    logoUrl: logo("darntough.com"),
    description: "Vermont-made merino wool socks, guaranteed for life.",
    shoppable: true,
    shopifyDomain: "www.darntough.com",
  },
  {
    id: "mystery_ranch",
    name: "Mystery Ranch",
    category: "Outdoor",
    domain: "mysteryranch.com",
    logoUrl: logo("mysteryranch.com"),
    description: "Technical packs and bags built for demanding use.",
    shoppable: true,
    shopifyDomain: "www.mysteryranch.com",
  },
  {
    id: "outdoor_research",
    name: "Outdoor Research",
    category: "Outdoor",
    domain: "outdoorresearch.com",
    logoUrl: logo("outdoorresearch.com"),
    description: "Technical outdoor apparel and gear.",
    shoppable: true,
    shopifyDomain: "www.outdoorresearch.com",
  },
  {
    id: "yeti",
    name: "YETI",
    category: "Outdoor",
    domain: "yeti.com",
    logoUrl: logo("yeti.com"),
    description: "Premium coolers, drinkware, and outdoor gear.",
    shoppable: true,
    shopifyDomain: "www.yeti.com",
  },
  {
    id: "hyperice",
    name: "Hyperice",
    category: "Fitness",
    domain: "hyperice.com",
    logoUrl: logo("hyperice.com"),
    description: "Recovery technology — ice compression and vibration.",
    shoppable: true,
    shopifyDomain: "www.hyperice.com",
  },
  {
    id: "trx",
    name: "TRX",
    category: "Fitness",
    domain: "trxtraining.com",
    logoUrl: logo("trxtraining.com"),
    description: "Suspension training systems and fitness equipment.",
    shoppable: true,
    shopifyDomain: "www.trxtraining.com",
  },
  // ── Health & Wellness ─────────────────────────────────────────────────────
  {
    id: "oura",
    name: "Oura Ring",
    category: "Wellness",
    domain: "ouraring.com",
    logoUrl: logo("ouraring.com"),
    description: "Smart ring for sleep and health tracking.",
    shoppable: true,
    shopifyDomain: "www.ouraring.com",
  },
  {
    id: "eight_sleep",
    name: "Eight Sleep",
    category: "Wellness",
    domain: "eightsleep.com",
    logoUrl: logo("eightsleep.com"),
    description: "Smart mattress covers for temperature-regulated sleep.",
    shoppable: true,
    shopifyDomain: "www.eightsleep.com",
  },
  {
    id: "ag1",
    name: "AG1",
    category: "Wellness",
    domain: "drinkag1.com",
    logoUrl: logo("drinkag1.com"),
    description: "Daily all-in-one nutritional supplement.",
    shoppable: true,
    shopifyDomain: "www.drinkag1.com",
  },
  {
    id: "ritual",
    name: "Ritual",
    category: "Wellness",
    domain: "ritual.com",
    logoUrl: logo("ritual.com"),
    description: "Clean, traceable daily vitamins.",
    shoppable: true,
    shopifyDomain: "www.ritual.com",
  },
  {
    id: "lmnt",
    name: "LMNT",
    category: "Wellness",
    domain: "drinklmnt.com",
    logoUrl: logo("drinklmnt.com"),
    description: "Zero-sugar electrolyte drink mixes.",
    shoppable: true,
    shopifyDomain: "www.drinklmnt.com",
  },
  {
    id: "bloom",
    name: "Bloom Nutrition",
    category: "Wellness",
    domain: "bloomsupps.com",
    logoUrl: logo("bloomsupps.com"),
    description: "Greens, collagen, and women's wellness supplements.",
    shoppable: true,
    shopifyDomain: "www.bloomsupps.com",
  },
  // ── Food & Beverage ───────────────────────────────────────────────────────
  {
    id: "magic_spoon",
    name: "Magic Spoon",
    category: "Other",
    domain: "magicspoon.com",
    logoUrl: logo("magicspoon.com"),
    description: "High-protein, low-carb grown-up cereal.",
    shoppable: true,
    shopifyDomain: "www.magicspoon.com",
  },
  {
    id: "death_wish_coffee",
    name: "Death Wish Coffee",
    category: "Other",
    domain: "deathwishcoffee.com",
    logoUrl: logo("deathwishcoffee.com"),
    description: "The world's strongest coffee.",
    shoppable: true,
    shopifyDomain: "www.deathwishcoffee.com",
  },
  {
    id: "olipop",
    name: "Olipop",
    category: "Other",
    domain: "drinkolipop.com",
    logoUrl: logo("drinkolipop.com"),
    description: "Prebiotic soda with real botanical ingredients.",
    shoppable: true,
    shopifyDomain: "www.drinkolipop.com",
  },
  {
    id: "atlas_coffee",
    name: "Atlas Coffee Club",
    category: "Other",
    domain: "atlascoffeeclub.com",
    logoUrl: logo("atlascoffeeclub.com"),
    description: "Single-origin coffee subscriptions from around the world.",
    shoppable: true,
    shopifyDomain: "www.atlascoffeeclub.com",
  },
  // ── Pet ───────────────────────────────────────────────────────────────────
  {
    id: "wild_one",
    name: "Wild One",
    category: "Other",
    domain: "wildone.com",
    logoUrl: logo("wildone.com"),
    description: "Modern pet accessories, leashes, and toys.",
    shoppable: true,
    shopifyDomain: "www.wildone.com",
  },
  {
    id: "ruffwear",
    name: "Ruffwear",
    category: "Outdoor",
    domain: "ruffwear.com",
    logoUrl: logo("ruffwear.com"),
    description: "Performance dog gear for outdoor adventures.",
    shoppable: true,
    shopifyDomain: "www.ruffwear.com",
  },
  // ── Kids ──────────────────────────────────────────────────────────────────
  {
    id: "primary",
    name: "Primary",
    category: "Apparel",
    domain: "primary.com",
    logoUrl: logo("primary.com"),
    description: "Colorful, affordable everyday kids' clothing.",
    shoppable: true,
    shopifyDomain: "www.primary.com",
  },

  // Directory-only merchants — in Affirm's real network, not yet live-queryable in this prototype
  {
    id: "peloton",
    name: "Peloton",
    category: "Fitness",
    domain: "onepeloton.com",
    logoUrl: logo("onepeloton.com"),
    description: "Bikes, treads, and fitness equipment.",
    shoppable: false,
  },
  {
    id: "walmart",
    name: "Walmart",
    category: "Other",
    domain: "walmart.com",
    logoUrl: logo("walmart.com"),
    description: "Everyday essentials at low prices.",
    shoppable: false,
  },
  {
    id: "best_buy",
    name: "Best Buy",
    category: "Electronics",
    domain: "bestbuy.com",
    logoUrl: logo("bestbuy.com"),
    description: "Electronics, appliances, and tech.",
    shoppable: false,
  },
  {
    id: "expedia",
    name: "Expedia",
    category: "Travel",
    domain: "expedia.com",
    logoUrl: logo("expedia.com"),
    description: "Flights, hotels, and vacation packages.",
    shoppable: false,
  },
  {
    id: "delta",
    name: "Delta",
    category: "Travel",
    domain: "delta.com",
    logoUrl: logo("delta.com"),
    description: "Flights and vacation packages.",
    shoppable: false,
  },
  {
    id: "adidas",
    name: "adidas",
    category: "Apparel",
    domain: "adidas.com",
    logoUrl: logo("adidas.com"),
    description: "Athletic apparel and footwear.",
    shoppable: false,
  },
  {
    id: "warby_parker",
    name: "Warby Parker",
    category: "Other",
    domain: "warbyparker.com",
    logoUrl: logo("warbyparker.com"),
    description: "Prescription eyewear and sunglasses.",
    shoppable: false,
  },
  {
    id: "wayfair",
    name: "Wayfair",
    category: "Home",
    domain: "wayfair.com",
    logoUrl: logo("wayfair.com"),
    description: "Furniture, decor, and home goods.",
    shoppable: false,
  },
  {
    id: "pottery_barn",
    name: "Pottery Barn",
    category: "Home",
    domain: "potterybarn.com",
    logoUrl: logo("potterybarn.com"),
    description: "Furniture, bedding, and home decor.",
    shoppable: false,
  },
  {
    id: "west_elm",
    name: "West Elm",
    category: "Home",
    domain: "westelm.com",
    logoUrl: logo("westelm.com"),
    description: "Modern furniture and home decor.",
    shoppable: false,
  },
  {
    id: "sephora",
    name: "Sephora",
    category: "Beauty",
    domain: "sephora.com",
    logoUrl: logo("sephora.com"),
    description: "Beauty, skincare, and fragrance.",
    shoppable: false,
  },
  {
    id: "nordictrack",
    name: "NordicTrack",
    category: "Fitness",
    domain: "nordictrack.com",
    logoUrl: logo("nordictrack.com"),
    description: "Treadmills, bikes, and home gym equipment.",
    shoppable: false,
  },
  {
    id: "hydrow",
    name: "Hydrow",
    category: "Fitness",
    domain: "hydrow.com",
    logoUrl: logo("hydrow.com"),
    description: "Connected rowing machines and fitness.",
    shoppable: false,
  },
  {
    id: "dyson",
    name: "Dyson",
    category: "Electronics",
    domain: "dyson.com",
    logoUrl: logo("dyson.com"),
    description: "Vacuums, air purifiers, and hair care.",
    shoppable: false,
  },
  {
    id: "purple",
    name: "Purple",
    category: "Mattresses",
    domain: "purple.com",
    logoUrl: logo("purple.com"),
    description: "Mattresses with GelFlex grid technology.",
    shoppable: false,
  },
  {
    id: "saatva",
    name: "Saatva",
    category: "Mattresses",
    domain: "saatva.com",
    logoUrl: logo("saatva.com"),
    description: "Luxury mattresses and bedroom furniture.",
    shoppable: false,
  },
  {
    id: "brilliant_earth",
    name: "Brilliant Earth",
    category: "Jewelry",
    domain: "brilliantearth.com",
    logoUrl: logo("brilliantearth.com"),
    description: "Ethically sourced fine jewelry.",
    shoppable: false,
  },
];

export const SHOPPABLE_MERCHANTS = MERCHANTS.filter((m) => m.shoppable);

export function findMerchant(id: string) {
  return MERCHANTS.find((m) => m.id === id);
}
